### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by denperss11** [cyberjunky/home-assistant-brandweerrooster#3]
Hello, 

When going to Goto Configuration -> Integrations, search for FireServiceRota and complete account data.

Fireservicerota is not showing up.. 

Ive installe the packaged from HACS and its install, i do also see it in custom componets folder... 

What to do '?

**Comment by filmgarage** [comment]
FireServiceRota is now a standard integration on Home Assistant. Simply update Home Assistant to version 2020.12 (minimum) and you will be able to add FireServiceRota on the integrations page. Please make sure to delete the old version on the integrations page if you managed to install it before. Next, delete the FireServiceRota folder in the custom_components folder before updating!!!

**Comment by denperss11** [comment]
My issue is that my HA is not allowing me to update to 2020.12
- Thats why i did this install..

**Comment by filmgarage** [comment]
I see, did you manually install the fireservicerota folder to the custom_components folder? I don't think you can actually install the FSR integration with HACS, only browser_mod etc...

**Comment by denperss11** [comment]
I got it working now from HACS :) 

Different issue is..When im going to love lace card and adding a manual card.. im getting No card type configured.


```
panel: true
title: Home
views:
  - badges: []
    cards:
      - entity: sensor.incidents
        type: entity
      - cards:
          - cards:
              - default_zoom: 15
                entities:
                  - entity: sensor.incidents
                hours_to_show: 0
                type: map
            type: vertical-stack
          - cards:
              - entities:
                  - entity: sensor.incidents
                hours_to_show: 1
                refresh_interval: 0
                type: history-graph
            type: vertical-stack
        type: horizontal-stack
      - content: |
          {{ states('sensor.incidents') }}
        title: Incident
        type: markdown
      - entities:
          - entity: binary_sensor.duty
          - entity: switch.incident_response
        type: entities
    path: fsr
    title: FireServiceRota
    type: horizontal-stack
```
