### ISSUE TITLE
Time bug.

### ISSUE THREAD

**Issue by denperss** [cyberjunky/home-assistant-brandweerrooster#6]
Issue when adding this to custom card. 
- it just shows up blank no time at the the card.

```
type: 'custom:bignumber-card'
entity: date.time
scale: 25px
```

**Comment by filmgarage** [comment]
You probably do not have a sensor.time

In Home Assistant you have to create these entities yourself.

Time sensor can be found on [Home Assistant Time & Date integration](https://www.home-assistant.io/integrations/time_date/)

Add this to your sensor setup:

```
sensor:
  - platform: time_date
    display_options:
      - 'time'
```
