### ISSUE TITLE
Cast FireServiceRota dashboard to Nest Hub issue

### ISSUE THREAD

**Issue by denperss** [cyberjunky/home-assistant-brandweerrooster#7]
When using this automation HA is not casting incident to the Nest hub screen. 

```
alias: Cast FireServiceRota dashboard to Nest Hub
description: ''
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: cast.show_lovelace_view
    data: {}
    entity_id: media_player.hub_devicename here
mode: single
```
